<?php
include("../../koneksi/konek.php");
//====================================================================
//Paging,Sorting dan Filter======
	$idPel=$_REQUEST['idPel'];
	$idKunj=$_REQUEST['idKunj'];
	$tgl=tglSQL($_REQUEST['tgl']);
	$formulir=addslashes($_REQUEST['formulir']);
	$jenis_darah=addslashes($_REQUEST['jenis_darah']);
	$alasan=addslashes($_REQUEST['alasan']);
	$urutan1=addslashes($_REQUEST['urutan1']);
	$urutan2=addslashes($_REQUEST['urutan2']);
	$urutan3=addslashes($_REQUEST['urutan3']);
	$urutan4=addslashes($_REQUEST['urutan4']);
	$pre=addslashes($_REQUEST['pre']);
	$a_pemberian_pre=addslashes($_REQUEST['a_pemberian_pre']);
	$kecepatan=addslashes($_REQUEST['kecepatan']);
	$target=addslashes($_REQUEST['target']);
	$pemeriksaan=addslashes($_REQUEST['pemeriksaan']);
	$laporan=addslashes($_REQUEST['laporan']);
	$dpjp=addslashes($_REQUEST['dpjp']);
	$nomor1=addslashes($_REQUEST['nomor1']);
	$utd1=addslashes($_REQUEST['utd1']);
	$tgl_k1=tglSQL($_REQUEST['tgl_k1']);
	$js_darah1=addslashes($_REQUEST['js_darah1']);
	$gol_darah1=addslashes($_REQUEST['gol_darah1']);
	$volume1=addslashes($_REQUEST['volume1']);
	$nomor2=addslashes($_REQUEST['nomor2']);
	$utd2=addslashes($_REQUEST['utd2']);
	$tgl_k2=tglSQL($_REQUEST['tgl_k2']);
	$js_darah2=addslashes($_REQUEST['js_darah2']);
	$gol_darah2=addslashes($_REQUEST['gol_darah2']);
	$volume2=addslashes($_REQUEST['volume2']);
	$nomor3=addslashes($_REQUEST['nomor3']);
	$utd3=addslashes($_REQUEST['utd3']);
	$tgl_k3=tglSQL($_REQUEST['tgl_k3']);
	$js_darah3=addslashes($_REQUEST['js_darah3']);
	$gol_darah3=addslashes($_REQUEST['gol_darah3']);
	$volume3=addslashes($_REQUEST['volume3']);
	$nomor4=addslashes($_REQUEST['nomor4']);
	$utd4=addslashes($_REQUEST['utd4']);
	$tgl_k4=tglSQL($_REQUEST['tgl_k4']);
	$js_darah4=addslashes($_REQUEST['js_darah4']);
	$gol_darah4=addslashes($_REQUEST['gol_darah4']);
	$volume4=addslashes($_REQUEST['volume4']);
	$jam1=addslashes($_REQUEST['jam1']);
	$jam2=addslashes($_REQUEST['jam2']);
	$jam3=addslashes($_REQUEST['jam3']);
	$jam4=addslashes($_REQUEST['jam4']);
	$kantong1=addslashes($_REQUEST['kantong1']);
	$pasien1=addslashes($_REQUEST['pasien1']);
	$k_kantong1=addslashes($_REQUEST['k_kantong1']);
	$transfusi1=addslashes($_REQUEST['transfusi1']);
	$jam5=addslashes($_REQUEST['jam5']);
	$jam6=addslashes($_REQUEST['jam6']);
	$jam7=addslashes($_REQUEST['jam7']);
	$jam8=addslashes($_REQUEST['jam8']);
	$kantong2=addslashes($_REQUEST['kantong2']);
	$pasien2=addslashes($_REQUEST['pasien2']);
	$k_kantong2=addslashes($_REQUEST['k_kantong2']);
	$transfusi2=addslashes($_REQUEST['transfusi2']);
	$jam9=addslashes($_REQUEST['jam9']);
	$jam10=addslashes($_REQUEST['jam10']);
	$jam11=addslashes($_REQUEST['jam11']);
	$jam12=addslashes($_REQUEST['jam12']);
	$kantong3=addslashes($_REQUEST['kantong3']);
	$pasien3=addslashes($_REQUEST['pasien3']);
	$k_kantong3=addslashes($_REQUEST['k_kantong3']);
	$transfusi3=addslashes($_REQUEST['transfusi3']);
	$jam13=addslashes($_REQUEST['jam13']);
	$jam14=addslashes($_REQUEST['jam14']);
	$jam15=addslashes($_REQUEST['jam15']);
	$jam16=addslashes($_REQUEST['jam16']);
	$kantong4=addslashes($_REQUEST['kantong4']);
	$pasien4=addslashes($_REQUEST['pasien4']);
	$k_kantong4=addslashes($_REQUEST['k_kantong4']);
	$transfusi4=addslashes($_REQUEST['transfusi4']);
	$nama1=addslashes($_REQUEST['nama1']);
	$nama2=addslashes($_REQUEST['nama2']);
	$nama3=addslashes($_REQUEST['nama3']);
	$nama4=addslashes($_REQUEST['nama4']);
	$nama5=addslashes($_REQUEST['nama5']);
	$nama6=addslashes($_REQUEST['nama6']);
	$nama7=addslashes($_REQUEST['nama7']);
	$nama8=addslashes($_REQUEST['nama8']);
	$idUsr=$_REQUEST['idUsr'];
	//$radio=$_REQUEST['radio'];
	/*$c_chk=$_REQUEST['c_chk'];
	for($i=0;$i<=3;$i++){
		$pilihan.=$c_chk[$i].',';
		}*/
	
	

switch(strtolower($_REQUEST['act'])){
	case 'tambah':
				$sql="INSERT INTO b_ms_catatan_transfusi (pelayanan_id,
				tgl,
				formulir,
				jenis_darah,
				alasan,
				urutan1,
				urutan2,
				urutan3,
				urutan4,
				pre,
				a_pemberian_pre,
				kecepatan,
				target,
				pemeriksaan,
				laporan,
				dpjp,
				nomor1,
				utd1,
				tgl_k1,
				js_darah1,
				gol_darah1,
				volume1,
				nomor2,
				utd2,
				tgl_k2,
				js_darah2,
				gol_darah2,
				volume2,
				nomor3,
				utd3,
				tgl_k3,
				js_darah3,
				gol_darah3,
				volume3,
				nomor4,
				utd4,
				tgl_k4,
				js_darah4,
				gol_darah4,
				volume4,
				jam1,
				jam2,
				jam3,
				jam4,
				kantong1,
				pasien1,
				k_kantong1,
				transfusi1,
				jam5,
				jam6,
				jam7,
				jam8,
				kantong2,
				pasien2,
				k_kantong2,
				transfusi2,
				jam9,
				jam10,
				jam11,
				jam12,
				kantong3,
				pasien3,
				k_kantong3,
				transfusi3,
				jam13,
				jam14,
				jam15,
				jam16,
				kantong4,
				pasien4,
				k_kantong4,
				transfusi4,
				nama1,
				nama2,
				nama3,
				nama4,
				nama5,
				nama6,
				nama7,
				nama8,
				tgl_act,
				user_act) 
				VALUES(
				'$idPel',
				'$tgl',
				'$formulir',
				'$jenis_darah',
				'$alasan',
				'$urutan1',
				'$urutan2',
				'$urutan3',
				'$urutan4',
				'$pre',
				'$a_pemberian_pre',
				'$kecepatan',
				'$target',
				'$pemeriksaan',
				'$laporan',
				'$dpjp',
				'$nomor1',
				'$utd1',
				'$tgl_k1',
				'$js_darah1',
				'$gol_darah1',
				'$volume1',
				'$nomor2',
				'$utd2',
				'$tgl_k2',
				'$js_darah2',
				'$gol_darah2',
				'$volume2',
				'$nomor3',
				'$utd3',
				'$tgl_k3',
				'$js_darah3',
				'$gol_darah3',
				'$volume3',
				'$nomor4',
				'$utd4',
				'$tgl_k4',
				'$js_darah4',
				'$gol_darah4',
				'$volume4',
				'$jam1',
				'$jam2',
				'$jam3',
				'$jam4',
				'$kantong1',
				'$pasien1',
				'$k_kantong1',
				'$transfusi1',
				'$jam5',
				'$jam6',
				'$jam7',
				'$jam8',
				'$kantong2',
				'$pasien2',
				'$k_kantong2',
				'$transfusi2',
				'$jam9',
				'$jam10',
				'$jam11',
				'$jam12',
				'$kantong3',
				'$pasien3',
				'$k_kantong3',
				'$transfusi3',
				'$jam13',
				'$jam14',
				'$jam15',
				'$jam16',
				'$kantong4',
				'$pasien4',
				'$k_kantong4',
				'$transfusi4',
				'$nama1',
				'$nama2',
				'$nama3',
				'$nama4',
				'$nama5',
				'$nama6',
				'$nama7',
				'$nama8',
				CURDATE(),
  				'$idUsr') ;";
		$ex=mysql_query($sql);
		//echo $sql;
		if($ex){
			echo "Data berhasil disimpan !";
			}else{
				echo "Data gagal disimpan !";
				}
	break;
	case 'edit':
		$sql="UPDATE b_ms_catatan_transfusi SET pelayanan_id='$idPel',
		tgl='$tgl',
		formulir='$formulir',
		jenis_darah='$jenis_darah',
		alasan='$alasan',
		urutan1='$urutan1',
		urutan2='$urutan2',
		urutan3='$urutan3',
		urutan4='$urutan4',
		pre='$pre',
		a_pemberian_pre='$a_pemberian_pre',
		kecepatan='$kecepatan',
		target='$target',
		pemeriksaan='$pemeriksaan',
		laporan='$laporan',
		dpjp='$dpjp',
		nomor1='$nomor1',
		utd1='$utd1',
		tgl_k1='$tgl_k1',
		js_darah1='$js_darah1',
		gol_darah1='$gol_darah1',
		volume1='$volume1',
		nomor2='$nomor2',
		utd2='$utd2',
		tgl_k2='$tgl_k2',
		js_darah2='$js_darah2',
		gol_darah2='$gol_darah2',
		volume2='$volume2',
		nomor3='$nomor3',
		utd3='$utd3',
		tgl_k3='$tgl_k3',
		js_darah3='$js_darah3',
		gol_darah3='$gol_darah3',
		volume3='$volume3',
		nomor4='$nomor4',
		utd4='$utd4',
		tgl_k4='$tgl_k4',
		js_darah4='$js_darah4',
		gol_darah4='$gol_darah4',
		volume4='$volume4',
		jam1='$jam1',
		jam2='$jam2',
		jam3='$jam3',
		jam4='$jam4',
		kantong1='$kantong1',
		pasien1='$pasien1',
		k_kantong1='$k_kantong1',
		transfusi1='$transfusi1',
		jam5='$jam5',
		jam6='$jam6',
		jam7='$jam7',
		jam8='$jam8',
		kantong2='$kantong2',
		pasien2='$pasien2',
		k_kantong2='$k_kantong2',
		transfusi2='$transfusi2',
		jam9='$jam9',
		jam10='$jam10',
		jam11='$jam11',
		jam12='$jam12',
		kantong3='$kantong3',
		pasien3='$pasien3',
		k_kantong3='$k_kantong3',
		transfusi3='$transfusi3',
		jam13='$jam13',
		jam14='$jam14',
		jam15='$jam15',
		jam16='$jam16',
		kantong4='$kantong4',
		pasien4='$pasien4',
		k_kantong4='$k_kantong4',
		transfusi4='$transfusi4',
		nama1='$nama1',
		nama2='$nama2',
		nama3='$nama3',
		nama4='$nama4',
		nama5='$nama5',
		nama6='$nama6',
		nama7='$nama7',
		nama8='$nama8',
		tgl_act=CURDATE(),
		user_act='$idUsr' WHERE id='".$_REQUEST['id']."'";
		//echo $sql;
		$ex=mysql_query($sql);
		if($ex){
			echo "Data berhasil disimpan !";
			}else{
				echo mysql_error();
				echo "Data gagal disimpan !";
				}
	break;
	case 'hapus':
		$sql="DELETE FROM b_ms_catatan_transfusi WHERE id='".$_REQUEST['id']."'";
		$ex=mysql_query($sql);
		if($ex){
			echo "Data berhasil dihapus !";
			}else{
				echo "Data gagal dihapus !";
				}
	break;
		
}
?>