<?php
include("../koneksi/konek.php");
//====================================================================
//Paging,Sorting dan Filter======
	$idPel=$_REQUEST['idPel'];
	$idKunj=$_REQUEST['idKunj'];
	$tgl_tiba=tglSQL($_REQUEST['tgl_tiba']);
	$tgl_kaji=tglSQL($_REQUEST['tgl_kaji']);
	$jam_kaji=$_REQUEST['jam_kaji'];
	$jam_tiba=$_REQUEST['jam_tiba'];
	$txt_diantar=addslashes($_REQUEST['txt_diantar']);
	$txt_protase=addslashes($_REQUEST['txt_protase']);
	$txt_penyakit=addslashes($_REQUEST['txt_penyakit']);
	$txt_diagnosa=addslashes($_REQUEST['txt_diagnosa']);
	$txt_rawatKpn=addslashes($_REQUEST['txt_rawatKpn']);
	$txt_dirawatDmn=addslashes($_REQUEST['txt_dirawatDmn']);
	$txt_sakitApa=addslashes($_REQUEST['txt_sakitApa']);
	$txt_pengobatan=addslashes($_REQUEST['txt_pengobatan']);
	$txt_alergiJns=addslashes($_REQUEST['txt_alergiJns']);
	$txt_tingBdn=addslashes($_REQUEST['txt_tingBdn']);
	$txt_brtBdn=addslashes($_REQUEST['txt_brtBdn']);
	$txt_TD=addslashes($_REQUEST['txt_TD']);
	$txt_HR=addslashes($_REQUEST['txt_HR']);
	$txt_RR=addslashes($_REQUEST['txt_RR']);
	$txt_Suhu=addslashes($_REQUEST['txt_Suhu']);
	$txt_minumX=addslashes($_REQUEST['txt_minumX']);
	$txt_minumCC=addslashes($_REQUEST['txt_minumCC']);
	$txt_BAK=addslashes($_REQUEST['txt_BAK']);
	$txt_BAKwarna=addslashes($_REQUEST['txt_BAKwarna']);
	$txt_muntahX=addslashes($_REQUEST['txt_muntahX']);
	$txt_muntahWarna=addslashes($_REQUEST['txt_muntahWarna']);
	$txt_muntahIsi=addslashes($_REQUEST['txt_muntahIsi']);
	$txt_hematX=addslashes($_REQUEST['txt_hematX']);
	$txt_hematJml=addslashes($_REQUEST['txt_hematJml']);
	$txt_tugor=addslashes($_REQUEST['txt_tugor']);
	$txt_edema=addslashes($_REQUEST['txt_edema']);
	$txt_BAB=addslashes($_REQUEST['txt_BAB']);
	$txt_BABcc=addslashes($_REQUEST['txt_BABcc']);
	$txt_melena=addslashes($_REQUEST['txt_melena']);
	$txt_melenaJml=addslashes($_REQUEST['txt_melenaJml']);
	$txt_fraktur=addslashes($_REQUEST['txt_fraktur']);
	$txt_score=addslashes($_REQUEST['txt_score']);
	$txt_invasif=addslashes($_REQUEST['txt_invasif']);
	$txt_infus=addslashes($_REQUEST['txt_infus']);
	$txt_plebitis=addslashes($_REQUEST['txt_plebitis']);
	$txt_kulitLok=addslashes($_REQUEST['txt_kulitLok']);
	$txt_kulitGrade=addslashes($_REQUEST['txt_kulitGrade']);
	$txt_kulitUkr=addslashes($_REQUEST['txt_kulitUkr']);
	$txt_tugorLok=addslashes($_REQUEST['txt_tugorLok']);
	$txt_edemaLok=addslashes($_REQUEST['txt_edemaLok']);
	$txt_nmObat=addslashes($_REQUEST['txt_nmObat']);
	$txt_intensitas=addslashes($_REQUEST['txt_intensitas']);
	$tgl_cerebal=tglSQL($_REQUEST['tgl_cerebal']);
	$tgl_gas=tglSQL($_REQUEST['tgl_gas']);
	$tgl_BJNTE=tglSQL($_REQUEST['tgl_BJNTE']);
	$tgl_termogulasi=tglSQL($_REQUEST['tgl_termogulasi']);
	$tgl_kebNutrisi=tglSQL($_REQUEST['tgl_kebNutrisi']);
	$tgl_volCairan=tglSQL($_REQUEST['tgl_volCairan']);
	$tgl_GPEU=tglSQL($_REQUEST['tgl_GPEU']);
	$tgl_GPEA=tglSQL($_REQUEST['tgl_GPEA']);
	$tgl_mobFisik=tglSQL($_REQUEST['tgl_mobFisik']);
	$tgl_integritas=tglSQL($_REQUEST['tgl_integritas']);
	$tgl_rawatDiri=tglSQL($_REQUEST['tgl_rawatDiri']);
	$tgl_psikiatrik=tglSQL($_REQUEST['tgl_psikiatrik']);
	$tgl_nyeri=tglSQL($_REQUEST['tgl_nyeri']);
	$penyakit='';
	
	
	$radio=$_REQUEST['radio'];
	$c_chk=$_REQUEST['c_chk'];
	
	$idUsr=$_REQUEST['idUsr'];
	
	for($i=0;$i<=5;$i++){
		$penyakit.=$c_chk[$i].',';
		}

switch(strtolower($_REQUEST['act'])){
	case 'tambah':
	$sql="INSERT INTO b_fom_chk_perawat (
  pelayanan_id,
  kunjungan_id,
  tgl_tiba,
  jam_tiba,
  tgl_kaji,
  jam_kaji,
  melalui,
  menggunakan,
  diantar,
  alat_protase,
  gelang,
  diagnosis,
  penyakit_skg,
  dirawat,
  pengobatan,
  alergi,
  tranfusi,
  penyakit_klg,
  kawin,
  motorik,
  berbicara,
  penglihatan,
  pendengaran,
  tinggi_badan,
  berat_badan,
  TD,
  suara_nafas,
  sputum,
  makan,
  frek_umum,
  BAK,
  muntah,
  hematemeis,
  asites,
  turgor,
  edema,
  BAB,
  peristaltik,
  melena,
  masalah_tdr,
  faktur,
  traksi,
  gibs,
  jatuh,
  invasif,
  infus,
  plebitis,
  mulut,
  gigi_palsu,
  kulit,
  turgor_2,
  edema_2,
  rambut,
  kebiasaan,
  emosi,
  skala_nyeri,
  g_cerebral,
  tgl_cerebral,
  g_gas,
  tgl_gas,
  g_jln_nafas,
  tgl_jln_nafas,
  g_termoregulasi,
  tgl_termoregulasi,
  g_keb_nutrisi,
  tgl_keb_nutrisi,
  g_vol_cairan,
  tgl_vol_cairan,
  g_eliminasi_u,
  tgl_eliminasi_u,
  g_eliminasi_a,
  tgl_eliminasi_a,
  g_mobilitas,
  tgl_mobilitas,
  g_integritas,
  tgl_integritas,
  g_rawat_diri,
  tgl_rawat_diri,
  g_psikiatrik,
  tgl_psikiatrik,
  g_nyeri,
  tgl_nyeri,
  tgl_act,
  user_act
) 
VALUES
  (
    '$idPel',
    '$idKunj',
    '$tgl_tiba',
    '$jam_tiba',
    '$tgl_kaji',
    '$jam_kaji',
    '$radio[0]',
    '$radio[1]',
    '$txt_diantar',
    '$radio[2]|$txt_protase',
    '$radio[3]',
    '$txt_diagnosa',
    '$txt_penyakit',
    '$radio[4]|$txt_rawatKpn|$txt_dirawatDmn|$txt_sakitApa',
    '$txt_pengobatan',
    '$radio[5]|$txt_alergiJns',
    '$radio[6]|$radio[7]',
    '$radio[8]|".substr($penyakit,0,-1)."',
    '$radio[15]',
    '$radio[9]',
    '$radio[10]',
    '$radio[11]',
    '$radio[12]',
    '$txt_tingBdn',
    '$txt_brtBdn',
    '$txt_TD|$txt_HR|$txt_RR|$txt_Suhu',
	'$radio[13]',
    '$radio[14]',
    '$radio[16]',
    '$txt_minumX|$txt_minumCC',
    '$txt_BAK|$txt_BAKwarna',
    '$txt_muntahX|$txt_muntahWarna|$txt_muntahIsi',
    '$txt_hematX|$txt_hematJml',
    '$radio[17]',
    '$radio[18]|$txt_tugor',
    '$radio[19]|$txt_edema',
    '$radio[20]|$txt_BAB|$txt_BABcc',
    '$radio[21]',
    '$txt_melena|$txt_melenaJml',
    '$radio[22]',
    '$txt_fraktur',
    '$radio[23]',
    '$radio[24]',
    '$txt_score',
    '$radio[25]|$txt_invasif',
    '$txt_infus',
    '$radio[40]|$txt_plebitis',
    '$radio[26]',
    '$radio[27]',
    '$radio[28]|$txt_kulitLok|$txt_kulitGrade|$txt_kulitUkr',
    '$radio[29]|$txt_tugorLok',
    '$radio[30]|$txt_edemaLok',
    '$radio[31]',
    '$radio[32]|$txt_nmObat',
    '$radio[33]',
    '$txt_intensitas',
    '$c_chk[6]',
    '$tgl_cerebal',
    '$c_chk[7]',
    '$tgl_gas',
    '$c_chk[8]',
    '$tgl_BJNTE',
    '$c_chk[9]|$radio[34]',
    '$tgl_termogulasi',
    '$c_chk[10]|$radio[35]',
    '$tgl_kebNutrisi',
    '$c_chk[11]|$radio[36]',
    '$tgl_volCairan',
    '$c_chk[12]|$radio[37]',
    '$tgl_GPEU',
    '$c_chk[13]|$radio[38]',
    '$tgl_GPEA',
    '$c_chk[14]',
    '$tgl_mobFisik',
    '$c_chk[15]',
    '$tgl_integritas',
    '$c_chk[16]',
    '$tgl_rawatDiri',
    '$c_chk[17]|$radio[39]',
    '$tgl_psikiatrik',
    '$c_chk[18]',
    '$tgl_nyeri',
    CURDATE(),
    '$idUsr'
  ) ;
";
		$ex=mysql_query($sql);
		if($ex){
			echo "Data berhasil disimpan !";
			}else{
				echo "Data gagal disimpan !";
				echo mysql_error();
				}
	break;
	case 'edit':
		$sql="UPDATE b_fom_chk_perawat SET
	pelayanan_id='$idPel',
  kunjungan_id='$idKunj', 
	tgl_tiba='$tgl_tiba',
  jam_tiba='$jam_tiba',
  tgl_kaji='$tgl_kaji',
  jam_kaji='$tgl_kaji',
  melalui='$radio[0]',
  menggunakan='$radio[1]',
  diantar='$txt_diantar',
  alat_protase='$radio[2]|$txt_protase',
  gelang='$radio[3]',
  diagnosis='$txt_diagnosa',
  penyakit_skg='$txt_penyakit',
  dirawat='$radio[4]|$txt_rawatKpn|$txt_dirawatDmn|$txt_sakitApa',
  pengobatan='$txt_pengobatan',
  alergi='$radio[5]|$txt_alergiJns',
  tranfusi='$radio[6]|$radio[7]',
  penyakit_klg='$radio[8]|".substr($penyakit,0,-1)."',
  kawin='$radio[15]',
  motorik='$radio[9]',
  berbicara='$radio[10]',
  penglihatan='$radio[11]',
  pendengaran='$radio[12]',
  tinggi_badan='$txt_tingBdn',
  berat_badan='$txt_brtBdn',
  TD='$txt_TD|$txt_HR|$txt_RR|$txt_Suhu',
  suara_nafas='$radio[13]',
  sputum='$radio[14]',
  makan='$radio[16]',
  frek_umum='$txt_minumX|$txt_minumCC',
  BAK='$txt_BAK|$txt_BAKwarna',
  muntah='$txt_muntahX|$txt_muntahWarna|$txt_muntahIsi',
  hematemeis='$txt_hematX|$txt_hematJml',
  asites='$radio[17]',
  turgor='$radio[18]|$txt_tugor',
  edema='$radio[19]|$txt_edema',
  BAB='$radio[20]|$txt_BAB|$txt_BABcc',
  peristaltik='$radio[21]',
  melena='$txt_melena|$txt_melenaJml',
  masalah_tdr='$radio[22]',
  faktur='$txt_fraktur',
  traksi='$radio[23]',
  gibs='$radio[24]',
  jatuh='$txt_score',
  invasif='$radio[25]|$txt_invasif',
  infus='$txt_infus',
  plebitis='$radio[40]|$txt_plebitis',
  mulut='$radio[26]',
  gigi_palsu='$radio[27]',
  kulit='$radio[28]|$txt_kulitLok|$txt_kulitGrade|$txt_kulitUkr',
  turgor_2='$radio[29]|$txt_tugorLok',
  edema_2='$radio[30]|$txt_edemaLok',
  rambut='$radio[31]',
  kebiasaan='$radio[32]|$txt_nmObat',
  emosi='$radio[33]',
  skala_nyeri='$txt_intensitas',
  g_cerebral='$c_chk[6]',
  tgl_cerebral='$tgl_cerebal',
  g_gas='$c_chk[7]',
  tgl_gas='$tgl_gas',
  g_jln_nafas='$c_chk[8]',
  tgl_jln_nafas='$tgl_BJNTE',
  g_termoregulasi='$c_chk[9]|$radio[34]',
  tgl_termoregulasi='$tgl_termogulasi',
  g_keb_nutrisi='$c_chk[10]|$radio[35]',
  tgl_keb_nutrisi='$tgl_kebNutrisi',
  g_vol_cairan='$c_chk[11]|$radio[36]',
  tgl_vol_cairan='$tgl_volCairan',
  g_eliminasi_u='$c_chk[12]|$radio[37]',
  tgl_eliminasi_u='$tgl_GPEU',
  g_eliminasi_a='$c_chk[13]|$radio[38]',
  tgl_eliminasi_a='$tgl_GPEA',
  g_mobilitas='$c_chk[14]',
  tgl_mobilitas='$tgl_mobFisik',
  g_integritas='$c_chk[15]',
  tgl_integritas='$tgl_integritas',
  g_rawat_diri='$c_chk[16]',
  tgl_rawat_diri='$tgl_rawatDiri',
  g_psikiatrik='$c_chk[17]|$radio[39]',
  tgl_psikiatrik='$tgl_psikiatrik',
  g_nyeri='$c_chk[18]',
  tgl_nyeri='$tgl_nyeri',
  tgl_act=CURDATE(),
  user_act='$idUsr' WHERE id='".$_REQUEST['txtId']."'";
		//echo $sql;
		$ex=mysql_query($sql);
		if($ex){
			echo "Data berhasil disimpan !";
			}else{
				echo mysql_error();
				echo "Data gagal disimpan !";
				}
	break;
	case 'hapus':
		$sql="DELETE FROM b_fom_chk_perawat WHERE id='".$_REQUEST['txtId']."'";
		$ex=mysql_query($sql);
		if($ex){
			echo "Data berhasil dihapus !";
			}else{
				echo "Data gagal dihapus !";
				}
	break;
		
}
?>